spring.application.name=cognify-journal


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Database Connection Settings using your .env file
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DDL Auto Generation Strategy (Tells Postgres to automatically create your tables)
spring.jpa.hibernate.ddl-auto=update

# Spring AI Ollama Configuration Settings
spring.ai.ollama.base-url=${AI_OLLAMA_BASE_URL}
spring.ai.ollama.embedding.options.model=nomic-embed-text